# Site settings
title: "Mariano's Blog"
subtitle: 
email: mravinale@gmail.com
description: 
baseurl: "http://mravinale.github.io"
url: "http://yourdomain.com"
twitter_username: mravinale
github_username:  mravinale
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
